### ISSUE TITLE
Create tests for the selected LRM chapters

### ISSUE THREAD

**Issue by tgorochowik** [SymbiFlow/sv-tests#71]
- [x] 5	Lexical conventions: PR: #21
- [x] 6	Data types #79
- [x] 7	Aggregate data types PR: #49
- [x] 8	Classes: PR: #52
- [x] 9	Processes: PR: #26
- [x] 11	Operators and expressions: PR: #73
- [x] 12	Procedural programming statements: PR: #44

Please update this issue with the relevant issues and PR to keep track of everything.
