### ISSUE TITLE
Add advanced simulation tests

### ISSUE THREAD

**Issue by piotr-binkowski** [SymbiFlow/sv-tests#819]
Currently we have only a basic set of simulation tests, we should add more tests for the following chapters:
- [x] 16. Assertions PR #821
- [x] 18. Constrained random value generation PR #820

Besides those chapters we should also cover some advanced simulation aspects like:
- [x] UVM Scoreboards PR #836
- [x] Bus functional models #836

While adding those tests we should also try to incorporate some tests utilizing UVM as it is used in real life simulation flows but its current test coverage needs improvement (#560).

Please update this issue with links to PRs/Issues to track status.
